[project]
name = "YTDownloader"
version = "1.4"
description = "A program to download any YouTube video or playlist"
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "realshouzy" }]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: Implementation :: CPython"
]
requires-python = ">=3.11"
dependencies = ["pytube", "PySimpleGUI"]

[tool.mypy]
strict = false
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
warn_redundant_casts = true

[tool.ruff]
extend-select = [
    "F", 
    "A", 
    "B", 
    "INP", 
    "I", 
    "PYI", 
    "RSE", 
    "RET", 
    "Q", 
    "SLF", 
    "SIM", 
    "TID", 
    "TCH", 
    "ARG", 
    "PL", 
    "RUF",
    "C4",
    "G",
    "COM",
    "BLE",
    "FBT"
]
ignore = ["E501", "PLR0912", "BLE001", "FBT003", "ARG002", "INP001"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
show-fixes = true
target-version = "py311"